apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  labels:
    #testing.upbound.io/example-name: example
  name: tha-example-1
spec:
  forProvider:
    delaySeconds: 90
    maxMessageSize: 2048
    messageRetentionSeconds: 86400
    name: tha-example-sqs-1
    receiveWaitTimeSeconds: 10
    region: us-east-1
    tags:
      Environment: production
