apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  labels:
    #testing.upbound.io/example-name: example
  name: tha-example-1
spec:
  forProvider:
    name: tha-example-sqs-1
    receiveWaitTimeSeconds: 10
    region: us-east-1
    redrivePolicy: >-
      ${jsonencode({
          deadLetterTargetArn = "arn:aws:sqs:us-east-1:153891904029:tha-example-sqs-1-dlq"
          maxReceiveCount     = 4
        })}
    tags:
      Environment: production
---

apiVersion: sqs.aws.upbound.io/v1beta1
kind: Queue
metadata:
  labels:
    #testing.upbound.io/example-name: example
  name: tha-example-1-dlq
spec:
  forProvider:
    name: tha-example-sqs-1-dlq
    receiveWaitTimeSeconds: 10
    region: us-east-1
    tags:
      Environment: production